### ISSUE TITLE
Link volunteers index from volunteer page

### ISSUE THREAD

**Issue by FedericoEsparza** [championer-org/championer_one#104]
**Hacktoberfest-friendly** ticket, open to anyone (I'll wait 24-hours before adding the `Hacktoberfest` label, to give current volunteers a first crack at it).
 
**Please move to `in progress` (or add the label), to indicate that you're working on it.**
 
We need to link the `/volunteers` path from the `/volunteer` page.
 
Let's start simple, and polish it later.
 
1.) Create the tests for the link:
   a.) Inside of `test/championer_one_web/acceptance/` create `page_volunteer_test.exs`
   b.) Add the following two tests, with the following use statements and setup:
```
defmodule ChampionerOneWeb.PageVolunteerTest do
  use ChampionerOneWeb.ConnCase
  use ExUnit.Case
  use Hound.Helpers

  hound_session()

  setup do
    conn = build_conn()
    navigate_to page_path(conn, :volunteer)
    {:ok, conn: conn}
  end

  test "text pointing to /volunteers exists" do
    assert page_source() =~ "See our list of volunteer contributors"
  end

  test "presence of /volunteers link", %{conn: conn} do
    find_element(:link_text, "here")
    |> click()
    assert current_path() == volunteer_path(conn, :index)
  end
end
```
   c.) Run the tests to make sure that they fail: `chromedriver & mix test test/championer_one_web/acceptance/page_volunteer_test.exs && pkill chromedriver`
 
2.) Add the text and link to make the tests pass:
  a) Open `lib/championer_one_web/templates/page/volunteer.html.eex` and add the following text and embedded elixir with the path helper:
   ```
<p>See our list of volunteer contributors <%= link "here", to: volunteer_path(@conn, :index) %>.</p>
   ```
  b.) Rerun the 2 tests to make sure they pass.
  c.) Run the entire test suite: `chromedriver & mix test && pkill chromedriver`
  d.) Test it out manually `open http://0.0.0.0:4000/volunteer && mix phx.server`

**Comment by justudin** [comment]
Hi @FedericoEsparza! I'd like to work on this :)
