### ISSUE TITLE
Overlay message and button over video

### ISSUE THREAD

**Issue by FedericoEsparza** [championer-org/championer_one#106]
**Hacktoberfest-friendly** ticket, open to anyone 

**Please move to `in progress` (or add the label), to indicate that you're working on it.**

We want to overlay a descriptive message and button over the background video.
 
1.) Create the tests:
   a.) Inside of `test/championer_one_web/acceptance/page_index_test.exs` add the following two tests:
```
  test "presence of video overlay message", %{conn: conn} do
    navigate_to page_path(conn, :index)
    assert page_source() =~ "We're a Tech Nonprofit"
    assert page_source() =~ "Volunteers design and develop prototypes and products that make a difference in the world"
  end

  test "Volunteer video overlay button works", %{conn: conn}  do
    navigate_to page_path(conn, :index)

    find_element(:class, "btn-overlay")
    |> click()
    assert current_path() == page_path(conn, :volunteer)
  end
```
   b.) Run the tests to make sure that they fail: `chromedriver & mix test test/championer_one_web/acceptance/page_index_test.exs && pkill chromedriver`
 
2.) Add the text and button to make the tests pass:
  a) Open `lib/championer_one_web/templates/layout/background_video.html.eex` and add the following text and embedded elixir anchor inside the `<div class="video-container">` and directly above the `<video autoplay preload="auto" loop class="fillWidth">` tag:
   ```
    <div class="video-overlay-container">
      <h2>We're a Tech Nonprofit</h2>
      <h5><em>Volunteers design and develop prototypes and products that make a difference in the world</em></h5>
      <a href="<%= page_path(@conn, :volunteer) %>" class="hide-on-small-only hoverable btn-large btn-overlay transparent waves-effect waves-light">Volunteer</a>
    </div>
   ```
  b.) Open `assets/css/background-video.scss` and add the following css selectors & properties:
   ```
.video-overlay-container {
    z-index: 200;
    position: absolute;
    font-family: 'Catamaran', sans-serif;
    width: 100%;
    color: #ffecb3;
    text-align: center;
}
.video-overlay-container h2 {
    color: #DED91C;
}
.btn-overlay {
    margin-top: 8rem;
    color: #ffecb3;
    border: 2px solid #DED91C;
}
.btn-overlay:hover, .btn-overlay:active {
    color: #DED91C;
    border: 2px solid #ffecb3;
    border-right: 3px solid #ffecb3;
    border-bottom: 3px solid #ffecb3;
}
   ```
  c.) Modify, inside the same file (`background-video.scss`), the `.filter` selector's `z-index` property to give it a value of 50, instead of 100:
   ```
.filter {
    z-index: 50;
   ```
  d.) Rerun the 2 tests to make sure they pass.
  e.) Run the entire test suite: `chromedriver & mix test && pkill chromedriver`
  f.) Test it out manually `open http://0.0.0.0:4000/ && mix phx.server`

**Comment by justudin** [comment]
I'll work on this. Thanks 👍
