### ISSUE TITLE
Add dotenv_elixir for database credentials

### ISSUE THREAD

**Issue by FedericoEsparza** [championer-org/championer_one#15]
Use [github.com/avdi/dotenv_elixir](https://github.com/avdi/dotenv_elixir) dep to switch `test` and `dev` database credentials to `.env` variables.
 
Not necessary for `prod`, as they have to be imported and compiled on the server, from untracked `config/prod.secret.exs`

**Comment by 3fernandez** [comment]
I don't know if we really need a dependency for this. There's a way of doing this in phoenix without adding a lib, by creating an `.env` file exporting all the credentials, add to `.gitignore` and then run `source .env` before `mix phx.server` or `source .env && mix phx.server`. But, there's a downside on this, you need to run `source .env` whenever you open a new terminal session.

And of course, we could overcome this by creating an system **alias** that run `source .env && mix phx.server` whenever we start the server, but at the same time I agree that it's not the best approach for new comers to the project.

So, If we decide go with the lib way, there is another lib with the same purpose, for us to take a look and evaluate. https://github.com/KamilLelonek/figaro-elixir

**Comment by FedericoEsparza** [comment]
Thanks, @3fernandez. Figaro-Elixir might also work. I'll test it out.

**Comment by FedericoEsparza** [comment]
Would create a hurdle, for new contributors, to getting their local environment set up. It's not worth the trouble, at this point.
 
Let's keep it painless, and we can revisit the issue down the line, if necessary.
