### ISSUE TITLE
Create and add new logo to landing page.

### ISSUE THREAD

**Issue by FedericoEsparza** [championer-org/championer_one#2]
Temporary logo has worn out its welcome:
![championer-logo](https://user-images.githubusercontent.com/11988089/36241742-b0a4004a-11dd-11e8-892e-b15c55231193.png)

Need something much more professional.
 
Can replace the Phoenix framework logo, for now.

**Comment by sigu** [comment]
I can pick this up @FedericoEsparza :smile:

**Comment by FedericoEsparza** [comment]
Sure, @Sigu. Feel free. I was thinking of using logojoy.com<http://logojoy.com>, to come up with something nice, but it would cost quite a bit.

Anything you want to try is fine with me. It can’t look much worse 😄

**Comment by vardyb** [comment]
@FedericoEsparza  Do we have an idea of a colour scheme we would want to implement?

**Comment by FedericoEsparza** [comment]
The color scheme is quite open. Especially if that helps you.

You’re welcome to reuse any of the current logo's colors, but like I mentioned, that logo was a temporary placeholder logo.

If you prefer to have some guidance on the colors, I can sort through some that I might personally like, but otherwise, use your artistic sense. Any color scheme is possible. Every color is at your disposal.

**Comment by vardyb** [comment]
@FedericoEsparza I've started to work on some basic logo drafts and kept the font and colour scheme generic so that we can discuss and agree on them at an point in the future.  PR created with first draft / thoughts on a logo.  Feedback (good or bad) welcomed.
