### ISSUE TITLE
Change site's background color, add background video/images

### ISSUE THREAD

**Issue by FedericoEsparza** [championer-org/championer_one#23]
Background color should probably be *teal darken-4.*
 
Search for and insert a 100%-width jumbotron image with an overlaid .32, or so, opacity black filter.

**Comment by FedericoEsparza** [comment]
I'm thinking of going with an autostart background video instead of an image for the home page.
 
An image on the rest, probably.

**Comment by FedericoEsparza** [comment]
@mattwr18 is this ticket just on-hold, or are you blocked by something?

**Comment by mattwr18** [comment]
@federico This is the ticket that I'm blocked on the background video implementation, do you remember? I talked to Euclides today to see if we can pair on it and he is going to get back to me, but he said he also doesn't have experience doing this. I was wondering if it wasn't a good candidate to work on the regular pairing session? Or maybe Brent would be able to help us out?

**Comment by FedericoEsparza** [comment]
@mattwr18 The open pairing session is 11 days away. Hopefully we can get it unblocked, before then.

**Comment by mattwr18** [comment]
@federico I had forgotten that it is bi-weekly, was expecting to pair this Monday... Euclides and I tried to get jQuery working, but were unsuccessful. 
He sent me a video that shows how we can add a background video with HTML5 and CSS. Let's see :)
