### ISSUE TITLE
Set up Hound

### ISSUE THREAD

**Issue by FedericoEsparza** [championer-org/championer_one#24]
Can follow instructions here:
https://hexdocs.pm/hound/readme.html
 
Let's test out ChromeDriver instead of PhantomJS:
https://github.com/HashNuke/hound/wiki/Starting-a-webdriver-server#starting-a-chromedriver-server

**Comment by FedericoEsparza** [comment]
@mattwr18 You might have already gotten this changed, but I looked up the precise `driver:` keyword value for chromedriver in the `config/config.exs` file:
 
`config :hound, driver: "chrome_driver", browser: "chrome_headless"`
 
https://github.com/HashNuke/hound/blob/master/notes/configuring-hound.md

**Comment by mattwr18** [comment]
Exactly what I have, even the source :)

**Comment by FedericoEsparza** [comment]
:+1:
