### ISSUE TITLE
Create initial navbar version with Materialize

### ISSUE THREAD

**Issue by FedericoEsparza** [championer-org/championer_one#3]
[http://materializecss.com/navbar.html](http://materializecss.com/navbar.html)
 
Tabs would be:
 - Mission
 - Volunteer
 - Donate
 - Products
 - Partners
 - Contact

**Comment by 3fernandez** [comment]
Hey @FedericoEsparza which approach do you prefer, via CDN or NPM?

**Comment by FedericoEsparza** [comment]
Hey, @3fernandez. Either is okay. If you want to work on it, whatever you're more comfortable with.
