### ISSUE TITLE
Add a footer with links

### ISSUE THREAD

**Issue by FedericoEsparza** [championer-org/championer_one#62]
Add a footer.
100% width. Outside the main container.
 
Now that we have Hound and Chromedriver set up, this one would be perfect to implement using Test-Driven Development.

In the `test/championer_one_web/acceptance/` folder, create a `layout_footer_test.exs`

Use `page_index_test.exs` as a guide to implement pure`page_path/2` navigation links for our site. In other words, don't use relative "hard-coded" paths, as in`navigate_to "/"`
 
Practice `outside ->  in` development, where you jump to unit tests to create controller tests, after you create acceptance tests that break on the third column links:

Failing Acceptance tests 
- -> Failing PageController `Terms of Use` test -> TDD implementation -> Green
- -> Failing PageController `Privacy Notice`test  -> TDD implementation -> Green
- -> Failing PageController `Sponsor Us` test  -> TDD implementation -> Green
- -> Failing PageController `Partner with Us` test  -> TDD implementation -> Green

Passing Acceptance tests 
 
Use [the Hound docs to find useful helper functions](https://hexdocs.pm/hound/api-reference.html#content)

Needs 3 columns.
 
One column with all the main Navbar links.

The second column with social media links.
Search `championer` in [namechk.com]( https://namechk.com) for 4 or 5 available social media sites where it's still available.
 
The Third column will have:
`Terms of Use`
`Privacy Notice`
`Sponsor Us`
`Partner with Us`
 
One of our logos could be at the bottom, along with copyright information.

**Comment by vardyb** [comment]
Do we also want to give the footer a background colour?

**Comment by FedericoEsparza** [comment]
@vardyb Yes, we do.

**Comment by FedericoEsparza** [comment]
The color can be a separate PR/issue, though, that finds just the right mix of colors throughout the page; especially if the code is ready for a PR, otherwise.

**Comment by vardyb** [comment]
Yep that makes good sense. Thanks.
