### ISSUE TITLE
Make navbar fixed and transparent (on load)

### ISSUE THREAD

**Issue by FedericoEsparza** [championer-org/championer_one#83]
Make navbar fixed and transparent (on load)
 
Let's give the pages a modern, single page app look, by making the nav transparent, on page load, placed at the top of the background video.
 
Then, as the page is scrolled down, use Materialize, jQuery, and CSS to transform it to the solid, nontransparent nav, fixed to the top. 

Specifically, that means removing the `transparent` class and adding the `navbar-fixed` class to the `nav` element, after the user scrolls past the height of the nav.

Use conditional logic in a new `assets/js/navbar.js` file to check whether scrolling has surpassed the height of the navbar, in order to dictate when the transformation jumps, for example: 
```js
if ($(window).scrollTop() > 50) {
    //add `navbar-fixed` && remove `transparent`class
} else {
    //add `transparent` && remove `navbar-fixed`class
}
```

Be sure to import jQuery into `assets/js/navbar.js`  as so: `import $ from "jquery"`
In turn, be sure to import `assets/js/navbar.js` into `assets/js/app.js` as so: `import "./navbar"`
 
The trickiest, and most time-consuming part, might end up being getting the transparent nav to properly overlay over the top of the background video, when the page is scrolled to the top.
 
This will probably require moving the navbar partial render code that is currently in `lib/championer_one_web/templates/layout/app.html.eex` out of there and inside the .`video-container` in the background-video partial.
 
This might even require some embedded elixir conditional logic in the app layout code.
 
Message me if you get stuck, so this doesn't become a CSS rabbit hole time consumer for you.

**Comment by mattwr18** [comment]
kinda blocked on this,  moving navbar partial to  inside the .video-container in the background-video partial causes the otherwise transparent navbar to turn black ..? 

![Screenshot at 2018-10-11 11:22:40.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0ffc32a47b6b0012fec340/125516c66e82c728ace21e0d46db978826878dba87e6ab03a549b0c679177f3e7854ee7a21c5b279e510295b5b5f5cb053181d1ba6acda6fb4bc2e75d85c0aeed23e5875c23b43a5ec821fb708b2298c4f85e3ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c48c15af043e04453a3133e71ab.png)

**Comment by FedericoEsparza** [comment]
@mattwr18  I pulled down the branch and just spent some time looking at it. I say we cut our losses and only make it fixed, as in my commit that I just pushed up.
 
I left the `navbar.js` file, so that we can pick this up down the line. We'll need a transparent logo.
 
But it looks good with just the fixed navbar, if you want to make the PR, so we can merge it and move on, for now.

**Comment by FedericoEsparza** [comment]
@mattwr18 This one literally just needs the PR from `83-navbar-fixed-transparent-on-load` and then a push of the `Update` (from develop) button, on the pull request page.
 
When you get a chance, could you do this, please?
