### ISSUE TITLE
Update README with contribution (PR) guidance

### ISSUE THREAD

**Issue by FedericoEsparza** [championer-org/championer_one#9]
Wafflebot has been enabled, so assignee can use this article for reference in updating README with condensed PR instructions: 
 
https://help.waffle.io/wafflebot-basics/getting-started-with-the-wafflebot/how-to-use-the-wafflebot

**Comment by FedericoEsparza** [comment]
@mattwr18 Looks good, so far: https://github.com/championer-org/championer_one/tree/9-update-readme-collaboration
 
Would you mind breaking up the text a little with some simple code-formatted examples, such as: `9-update-readme-collaboration` or `1-NAME-OF-FEATURE-OR-ISSUE`?

AND 
 
`closes #9` or `fixes #1`

 
A screenshot or two would be nice, as well.
 
You might use this one:  
`![waffle in progress](https://dl.dropbox.com/s/l7iw1e1867btvwj/Screenshot%202018-06-01%2012.09.18.png)`
![waffle in progress](https://dl.dropbox.com/s/l7iw1e1867btvwj/Screenshot%202018-06-01%2012.09.18.png)
 
Maybe also add the Waffle Help link.

**Comment by mattwr18** [comment]
Cool! I'm on it! :)
