### ISSUE TITLE
Add Volunteer schema

### ISSUE THREAD

**Issue by FedericoEsparza** [championer-org/championer_one#94]
Follow most of the steps in this concise tutorial: https://alchemist.camp/episodes/pretty-url-phoenix-params
 
We already have an app obviously, so don't recreate one.
 
When using the html generator, go with a `Volunteers` context instead of the `Core` context; and replace the `User` schema with a `Volunteer` schema; and finally go with a `volunteers` database table instead of `users`.
 
The fields for the schema should just be `name`, `github_username` (make it unique), for now. We'll add more, as needed, later.
 
SO THE GENERATOR COMMAND should be `mix phx.gen.html Volunteers Volunteer volunteers name:string github_username:string:unique`
 
You'll want to update `router.ex` with `resources "/volunteers", VolunteerController` in the root scope.

With the files generated, you WON'T need to edit the new migration file, like in the video, to index `name` in the database, inside the change function, as in: `create index(:volunteers, [:name])`, because the generator will have created `create unique_index(:volunteers, [:github_username])` for you.
 
Don't forget to run the migration: `mix ecto.migrate`

Be sure to follow the instructions to convert the url paths to name urls BUT with `github_username` instead (follow these steps):
     
In `lib/championer_one/volunteers/volunteer.ex`, above the schema definition, add `@derive {Phoenix.Param, key: :github_username}`
 
In `lib/championer_one/volunteers/volunteers.ex`, change the `get_volunteer` context API function to `def get_volunteer!(github_username), do: Repo.get_by!(Volunteer, %{github_username: github_username})`

The app volunteer CRUD features should work at this point(`open http://0.0.0.0:4000/volunteers && mix phx.server`), but you'll get failing generated tests (`chromedriver & mix test && pkill chromedriver)`

To get them to pass, in `test/championer_one/volunteers/volunteers_test.exs`, search for occurrences of `volunteer.id` and change them to `volunteer.github_username`

And in `test/championer_one_web/controllers/volunteer_controller_test.exs`, change the `github_username:` value in the `@create_attrs` and the `@update_attrs` module attributes to `"some_github_username"` and `"some_updated_github_username"`, respectively. In other words, convert them to one word values--no spaces.
 
In that same file (`volunteer_controller_test.exs`), in the `describe "update volunteer" test "redirects when data is valid"` test, you'll want to replace the following line:

```
      assert redirected_to(conn) == volunteer_path(conn, :show, volunteer)
```
with these two lines: 
```
      assert %{id: id} = redirected_params(conn)
      assert redirected_to(conn) == volunteer_path(conn, :show, id)
```
And in the same test, replace:
```
      conn = get conn, volunteer_path(conn, :show, volunteer)
      assert html_response(conn, 200) =~ "some updated github_username"
```
with:
```
      conn = get conn, volunteer_path(conn, :show, id)
      assert html_response(conn, 200) =~ "some_updated_github_username"
 ```
Reach out if you have any questions.

**Comment by justudin** [comment]
I'd like to work on this :)

**Comment by FedericoEsparza** [comment]
@justudin That's great! You're quite welcome to do so! @Kachulio1 and @faithngetich have not gotten around to working on it, although it was never officially assigned to them. 

You might check in with them, however, in the Slack channel [(#phoenix_one)](https://agileventures.slack.com/messages/phoenix_one) for the project. Tag `@faith` and `@joseph` and see if they want to, maybe, work on it with you.
 
I've invited you as a collaborator to the project (https://github.com/championer-org/championer_one/invitations). Please follow the README instructions for working on a ticket. 
 
If Faith and Joseph don't protest, or don't want to pair on the ticket, go ahead and work on it. Let me know if you have any questions.

**Comment by justudin** [comment]
Ah sorry. Just read your comment after finishing the issue :). 
Ok I will check it on slack. Thank you :)
