### ISSUE TITLE
add LiveView

### ISSUE THREAD

**Issue by FedericoEsparza** [championer-org/championer_one#95]

**Comment by FedericoEsparza** [comment]
Do we need to upgrade to Phx 1.4?

**Comment by justudin** [comment]
I guess there is existing "Drab - https://tg.pl/drab" module for that without upgrading the Phx version. 
As I understood, it kind of real-time client-side manipulation/handling from server side. 
What do you think?

**Comment by FedericoEsparza** [comment]
Not sure. I haven't looked into Drab. Chris McCord said he'd release Phoenix.LiveView after he first released Phx 1.4, and Phx 1.4.0-rc.2 was just recently released, so we might just wait. 
 
I guess LiveView will have versioning independent of Phx, but I'm still not sure if we'd need to update.
 
I think we'll update anyway, eventually.

**Comment by FedericoEsparza** [comment]
It's finally been released: https://github.com/phoenixframework/phoenix_live_view

You'll have to get up to speed on how it works (https://github.com/phoenixframework/phoenix_live_view#learning).

Once you do, you'll have `championer_one` to try it out!
